fede1024/rust-rdkafka

- src/error.rs
Implement these traits so it's possible to integrate `KafkaError` with normal Rust error handling and libraries such as `error-chain`.
> Implement Error, Debug and Display for KafkaError

- src/config.rs
- src/consumer/stream_consumer.rs
- src/producer.rs
- src/topic_partition_list.rs
I was ruling out some issues in a crash, this helped.
> Use expects with a description instead of unwraps

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/producer.rs
- src/topic_partition_list.rs
- tests/produce_consume_base_test.rs
We needed more control over committing in our project, so I added the other commit function from `rdkafka` too.
> Fix tests & commit list of partitions and offsets

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- tests/produce_consume_base_test.rs
Add various metadata that is available for a consumer.
> More metadata

- Cargo.toml
- src/client.rs
- src/lib.rs
- src/producer.rs
- src/statistics.rs
- tests/test_utils.rs
We could consider making the field names more self-explanatory and adding some docs.
> Parse statistics to struct

- Cargo.toml
- README.md
- rdkafka-sys/Cargo.toml
- src/lib.rs
Haven't updated the binding, there are some additions but nothing that's incompatible.
> Bump rdkafka to 0.9.4

- examples/asynchronous_processing.rs
- examples/simple_producer.rs
- rdkafka-sys/README.md
- rdkafka-sys/src/bindings/mod.rs
- src/message.rs
- src/producer.rs
- tests/produce_consume_base_test.rs
- tests/test_utils.rs
> Timestamps

- src/client.rs
- src/producer.rs
Make some changes in behaviour to make sure we implement this properly:
https://github.com/edenhill/librdkafka/wiki/Proper-termination-sequence
> Termination fixes

- rdkafka-sys/src/helpers.rs
- rdkafka-sys/src/types.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/error.rs
- src/producer.rs
- src/topic_partition_list.rs
Make it easier to pattern match on the underlying rdkafka errors.
> Add nice error wrapper

- src/groups.rs
cc https://github.com/fede1024/kafka-view/issues/16
> Expose metadata and assignment on GroupMemberInfo

- src/producer/future_producer.rs
Add `send_copy_result` method to future producer that restores the behaviour that was removed in #53
> Add send_copy_result to producer

- Cargo.toml
- Dockerfile
- rdkafka-sys/Cargo.toml
- rdkafka-sys/build.rs
> Build librdkafka with cmake

- src/error.rs
> fix doc typo

- examples/asynchronous_processing.rs
The tokio::executor::{current_thread, thread_pool} exports have been
deprecated since Tokio v1.8. Use the newer runtime APIs instead. There
is no functionality change; this just makes the asynchronous_processing
exampleclearer for folks who are new to the Tokio ecosystem.
> examples/asynchronous_processing: use updated Tokio API

- rdkafka-sys/src/bindings.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/error.rs
- src/message.rs
- src/producer/base_producer.rs
- src/util.rs
The first three commits are #119. I'll rebase if/when that merges.
> Address clippy lints

- Cargo.toml
- rdkafka-sys/Cargo.toml
- rdkafka-sys/build.rs
- rdkafka-sys/src/helpers.rs
- rdkafka-sys/src/types.rs
Also update bindgen dependency to latest version. Fixes #132
> Update librdkafka to 1.0.1

- src/client.rs
- src/config.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/util.rs
try to fix build error in aarch64 Architecture.
the issue is #121
> Fix arm build

- .travis.yml
- Cargo.toml
- Dockerfile
- docker/run_tests.sh
- rdkafka-sys/Cargo.toml
- src/config.rs
- src/error.rs
Also bump bindgen to a version that doesn't overflow the stack on the
beta/nightly Rust compilers.
This PR is a combination of #150 and #151. Fixes #148.
> Upgrade to librdkafka v1.2.1

- src/util.rs
- tests/test_low_producers.rs
> Implement IntoOpaque for Arc<T>

- examples/at_least_once.rs
- examples/simple_consumer.rs
- rdkafka-sys/build.rs
- tests/test_consumers.rs
See comment within for explanation.
> rdkafka-sys: don't let CMake install to lib64

- src/client.rs
- src/consumer/base_consumer.rs
Looked into if there was an obvious fix for #220 but nothing so far. Still this improves things a bit.
> refactor: Remove the need for mem::forget in some cases

- rdkafka-sys/README.md
- rdkafka-sys/build.rs
Update docs and tweak the CMake build system. Details in commit messages.
> rdkafka-sys: improve sasl2 vendoring

- src/client.rs
Allows for the null pointer optimization to be used in `Option`s etc.
Split out from #241.
> Use NonNull in NativeClient

- src/producer/base_producer.rs
The JoinHandle is only accessed by the thread that holds the
ThreadedProducer, so it doesn't need to be wrapped in a RwLock. The
stop signal is already made threadsafe by use of an atomic bool.
> Avoid unnecessary lock in threaded producer

- CONTRIBUTING.md
- README.md
- generate_readme.py
- rdkafka-sys/CONTRIBUTING.md
- rdkafka-sys/README.md
- rdkafka-sys/readme_template
- rdkafka-sys/src/helpers.rs
- rdkafka-sys/src/lib.rs
- rdkafka-sys/src/types.rs
- readme_template
- src/client.rs
- src/config.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/error.rs
- src/groups.rs
- src/lib.rs
- src/message.rs
- src/metadata.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
- src/producer/mod.rs
- src/statistics.rs
- src/topic_partition_list.rs
- src/util.rs
- tests/test_high_consumers.rs
Enforce a more consistent style on the docs. Also correct a number of
typos and stale information.
> Rework documentation

- src/consumer/base_consumer.rs
- tests/test_low_consumers.rs
See the comment within for details. This permits moving partition queues
to other threads safely.
> Implement split_partition_queue on Arc<Self>, not &self

- changelog.md
- src/consumer/base_consumer.rs
- src/consumer/stream_consumer.rs
> Respect max.poll.interval.ms in StreamConsumer

- src/consumer/stream_consumer.rs
See https://github.com/fede1024/rust-rdkafka/issues/247#issuecomment-655553913
for details. The gist is that while failing to `await` a StreamConsumer
within the max poll interval should result in tripping the timeout, as
long as you are calling `await`, we should periodically poll the
consumer.
> Ensure stream consumers on empty topics do not exceed max poll interval

- src/error.rs
Also remove the deprecated error methods; description is replaced by the
error's fmt::Display implementation, and cause is replaced by source.
> Make it easier to retrieve underlying RDKafkaError

- Cargo.toml
- src/util.rs
- tests/test_admin.rs
- tests/test_high_consumers.rs
Hi @benesch  🙋🏻‍♂️,
Just a little a PR to update tokio (there is an incompatibility with 0.2/0.3 runtime), let me know if something is missing 👍
> deps: update to tokio v0.3.0

- Cargo.toml
- examples/smol_runtime.rs
update examples to newer smol version
> Update to newer smol runtime

- src/consumer/stream_consumer.rs
If there's a message available, we can avoid taking a lock.
> Optimistically avoid locking in StreamConsumer

- src/admin.rs
- src/client.rs
- src/config.rs
- src/util.rs
- tests/test_high_consumers.rs
This regressed since the last release.
> Fix error buffers

- src/config.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
> Improve `set` method of `ClientConfig`

- src/producer/base_producer.rs
I missed this one in https://github.com/fede1024/rust-rdkafka/pull/440
cc @benesch
> convert final log line to `crate::log`

- src/consumer/mod.rs
Per the discussion here: https://github.com/fede1024/rust-rdkafka/issues/448
Feel free to make any other documentation suggestions here as well.
> Improve documentation of CommitMode enum

- changelog.md
> Add missing changelog items for v0.29.0

- src/client.rs
Add a method to fetch cluster id in Client
> Add a client method to fetch cluster_id

- README.md
- src/lib.rs
👋 A small change that adds in the README a new project that is using rust-rdkafka. Thanks for all the work on this.
> Add a new project using rust-rdkafka

- changelog.md
- rdkafka-sys/changelog.md
- rdkafka-sys/src/types.rs
- src/admin.rs
- tests/test_admin.rs
Resubmission of #510, since I don't have access to @andrewinci's remote.
> Support delete groups in the admin client

- changelog.md
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
> Expose seek_partitions

- src/topic_partition_list.rs
Fixes https://github.com/fede1024/rust-rdkafka/issues/681
> fix: check for non-zero count before calling slice::from_raw_parts_mut

- rdkafka-sys/src/types.rs
- src/admin.rs
- src/util.rs
- tests/test_admin.rs
Fix https://github.com/fede1024/rust-rdkafka/issues/385.
> Add support for deleting records to admin client

- src/client.rs
- src/config.rs
Transition from callbacks to events changed log handling for librdkafka's internal threads - logs are sent to stderr (default in librdkafka).
This PR fixes it and restores previous forwarding behavior.
> fix: forward log messages

- README.md
- src/lib.rs
> doc: Fix broken "Transaction" link

- src/producer/base_producer.rs
---
>Sponsored by [Quad9](https://quad9.net/)
> Handle null characters in topic in BaseProducer::send
