- rdkafka-sys/Cargo.toml
- rdkafka-sys/src/lib.rs
The separate `lz4-sys` crate was published, so we can re-add the dependency.
> Add lz4-sys crate

- examples/simple_consumer.rs
- src/client.rs
- src/config.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/lib.rs
- src/topic_partition_list.rs
- src/util.rs
The rebalance callback uses the same data structure that's used for managing subscriptions. This adds a wrapper around this structure which now is also used when subscribing.
Currently there's no way to get rebalance events in the streaming consumer. Not sure how to do that yet.
> Topic partition list and rebalance callback

- .travis.yml
- README.md
- examples/simple_consumer.rs
- examples/simple_producer.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/error.rs
- tests/produce_consume_base_test.rs
Add separate function to manually assign a topic/partition list for a consumer. Change back `subscribe` to accept a vector of strings to set the correct expectation on how to use it.
Based on #8, will rebase once that's merged.
> Add manual assignement to consumer

- src/client.rs
- src/config.rs
Pipe rdkafka logs to Rust logging, so they show up in the same format and with the same levels as your normal logs.
> Integrate rdkafka logging with log crate

- src/producer.rs
I need this for the type signature of one of the structs in our project.
> Make EmptyProducerContext public

- rdkafka-sys/src/types.rs
- src/config.rs
It's usually already displayed by the log implementation on the Rust side, so this results in duplicate output in the log.
> Remove log level from log callback

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
I like this pattern of storing the integer representation in the enum itself.
> Store integer value in CommitMode enum

- Cargo.toml
- tests/produce_consume_base_test.rs
Seems to compile; this change will allow folks to use the current version of `tokio` in the same project as `rust-rdkafka`.
> Bump to futures 0.1.7

- src/config.rs
- src/consumer/stream_consumer.rs
Two minor logging improvements:
* Change rdkafka prefix to librdkafka to make it more clear that these messages originate from the C
library.
* Add trace log to streaming consumer poll loop
> More specific logging

- src/producer.rs
- tests/produce_consume_base_test.rs
This makes it possible to match on the report instead of resorting to using `is_error` and `resp_err_description` manually.
> Return a result for a DeliveryReport

- Cargo.toml
- README.md
- rdkafka-sys/Cargo.toml
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/lib.rs
- tests/test_utils.rs
Rdkafka takes care of thread safety itself, do Rust doesn't need to enforce this for us. Completely removes the `get_base_consumer_mut` function.
This is based of #37, so that should be merged before this one.
> Make subscribe and assign take a non-mutable self

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- tests/produce_consume_base_test.rs
This allows you to look up the first offset for a certain timestamp.
It is possible to have a separate timestamp per partition, but we don't need this for our use case. We could add a `offsets_for_timestamps` that takes a map of partition/timestamp as well later if the need arises.
> Add offsets_for_timestamp to consumer

- rdkafka-sys/Cargo.toml
We don't need to build openssl if the ssl feature isn't selected.
This was preventing me from building rust-rdkafka with musl.
> Make OpenSSL dependency optional

- src/message.rs
It's not needed because Rust will infer the correct lifetime. Leaving it out makes it easier to work with messages from client code. Also adds `Clone` and `Copy` derives to `Timestamp`.
> Remove explicit lifetime for Message

- examples/asynchronous_processing.rs
- examples/at_least_once.rs
- examples/simple_producer.rs
- src/error.rs
- src/producer.rs
- tests/test_utils.rs
Returning a Result made it very difficult to use `send_copy()` in a chain of futures, and, since a Future is just an asynchronous Result, this commit changes the DeliveryFuture to yield a KafkaError on failure. Previously, the DeliveryFuture would only yield Canceled, and, to continue supporting this, a new variant of KafkaError was added, `FutureCanceled`.
This makes the FutureProducer API considerably more ergonomic. For example, in a function which returns a `BoxFuture<(), ::std::io::Error>`, this is what was necessary before:
```rust
return match kafka_producer.send_copy::<_, ()>(
"test", None, Some(&*format!("msg on {}", topic)), None, None) {
Ok(report) => {
report
.map_err(|_| io::Error::new(io::ErrorKind::Other,
"failed to send kafka message"))
.and_then(|_| future::ok(())) …
```
> Directly return a DeliveryFuture from FutureProducer::send_copy

- rdkafka-sys/build.rs
Don't build examples.
I got some errors when cross compile to x86_64-unknown-linux-musl target, it was caused by librdkafka examples compiling, somehow `ld` it used isn't the cross compiling one but the host one. Disable librdkafka examples build fixed it.
As for `rust-rdkafka`, the librdkafka examples isn't really useful anyway.
https://github.com/edenhill/librdkafka/blob/7fada8feaa4d8b0450fb9027347ac80d29d4388d/Makefile#L19
> Only build librdkafka libs

- changelog.md
- examples/metadata.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
- src/util.rs
- tests/test_consumers.rs
- tests/test_metadata.rs
- tests/test_producers.rs
Using i32 for milliseconds, with special case of -1 as no timeout, is
error prone and less self-documenting.
I tried to replace all externally-looking timeouts with the proper timeout encapsulation. What I'm not entirely sure of:
* If all them allow the `None`/-1 case for infinite timeout (I guess they probably do, but I haven't gone reading the rdkafka docs)
* That I got them all ‒ it was more of a search&replace than reading it manually from start to end.
* I also thought about taking `T: Into<Option<Duration>>` as the parameter. That would allow calling `poll(Duration::from_secs(10)` as well as `poll(None)`. While this is a bit less typing, it is also potentially bit more confusing and it would make certain traits not object safe, so I left it with this.
> WIP: Use Option<Duration> for timeouts

- src/producer/mod.rs
It seems that `DeliveryFuture` was left out from the reexported producer structs. This change fixes this omission, making possible to use `FutureProducer::send_copy_result()` by using just `rdkafka::producer::*` rather than having to include the struct from the `future_producer` module.
> Reexport DeliveryFuture from the producer module

- changelog.md
- src/consumer/base_consumer.rs
- tests/test_consumers.rs
Allow iterating over the consumer instead of calling poll to get the
messages.
I didn't find any test for the base consumer ‒ should I try creating one, to test the iterator?
> Iterator interface for the consumer

- src/consumer/base_consumer.rs
- tests/test_consumers.rs
As the result of the talk we had online, this retries inside the iterator if the poll returns no message (it still returns the errors).
Also, got rid of the timeout, as it looks strange on the iterator and would terminate it „randomly“, which would probably be strange.
> Simplify the iterator interface

- src/lib.rs
To link to the *same* version of documentation, not the newest (could be
confusing if someone explicitly looks through older version), or to the
local one in case of development version or offline usage.
> Make documentation links relative if possible

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
This method allows to specify a TPL for which to get committed offsets.
The main reason is to allow getting committed offsets without/before subscribing to anything.
> Added `committed_offsets` method

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
This method allows to specify a TPL for which to get offsets.
The main reason is to allow getting offsets for timestamps without/before subscribing to anything.
> Added `offsets_for_times` method

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
`tpl` should be mutable in the rebalance hook.
An example: https://github.com/edenhill/librdkafka/blob/bd74dc31ba6edf431749b4ad5a00aa4fc78882fc/tests/0029-assign_offset.c#L70
> Made `tpl` in `rebalance` mutable

- Cargo.toml
- docker-compose.yaml
- rdkafka-sys/build.rs
- rdkafka-sys/src/types.rs
- src/admin.rs
- src/client.rs
- src/config.rs
- src/error.rs
- src/lib.rs
- src/util.rs
- tests/test_admin.rs
- tests/test_metadata.rs
- tests/utils.rs
There's probably a few more bugs here to shake out, but this is mostly ready to go.
~This is based off of #119/#120. It's not technically tied to any of the changes in #119/#120, if for some reason we want to land this before those PRs.~
Fix #92.
> Add admin API client

- rdkafka-sys/build.rs
std::process::Command is known to be unpredictable when a relative path
is used together with `current_dir`, and outright fails on macOS
Catalina [0]. Absolutize paths before passing them to
std::process::Command to stay within the documented constraints of the
API.
[0]: https://github.com/rust-lang/rust/issues/37868
Supersedes #160.
> Avoid use of undefined std::process::Command behavior

- .travis.yml
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/util.rs
Incorporate @jerry73204's ARM fixes from #155, and also add a Travis CI job that actually tests the ARM build, to prevent regressions in the future.
Fix #121.
> Fix ARM build, and test it in CI

- examples/asynchronous_processing.rs
- examples/simple_producer.rs
- src/producer/mod.rs
- tests/test_high_producers.rs
- tests/test_low_producers.rs
- tests/utils.rs
This is no longer necessary, as librdkafka unconditionally sends the
offset report to producers.
Fix #139.
> Remove references to deprecated produce.offset.report config

- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/error.rs
- tests/test_consumers.rs
Closes https://github.com/fede1024/rust-rdkafka/issues/153
> Implement pause/resume for Consumer

- rdkafka-sys/Cargo.toml
Bump to a version of zstd-sys that properly copies all public header
files into DEP_ZSTD_ROOT. The old version of zstd-sys was not exposing
the zstd_errors.h header file.
Details: https://github.com/gyscos/zstd-rs/pull/68
> rdkafka-sys: bump zstd-sys for build fix

- src/admin.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/error.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
- src/util.rs
- tests/test_admin.rs
- tests/test_consumers.rs
This makes it possible to receive a notification via a Rust callback when there are new messages available. The bulk of the implementation is in the last two commits; the first commit is just preparatory work.
> Plumb message_queue_nonempty callback

- .travis.yml
- rdkafka-sys/build.rs
Builds on Windows with MSVC environment produce the library located at `build/src/Release` or `build/src/Debug`, instead of just `build/src` for other environments.
This PR explicitly handles this case. The choice between `Release` and `Debug` happens using the same logic as in `cmake` crate, see [these lines](https://docs.rs/cmake/0.1.26/src/cmake/lib.rs.html#329-333).
> Support CMake build on MSVC

- .travis.yml
- Cargo.toml
- README.md
- changelog.md
- rdkafka-sys/Cargo.toml
- rdkafka-sys/README.md
- rdkafka-sys/build.rs
- rdkafka-sys/src/helpers.rs
- rdkafka-sys/src/lib.rs
- rdkafka-sys/src/types.rs
Probably easiest just to look at the commit messages and the updates to the changelog/README.
> Improve build system + prepare for 0.22

- Cargo.toml
- changelog.md
- examples/asynchronous_processing.rs
- examples/at_least_once.rs
- examples/simple_consumer.rs
- examples/simple_producer.rs
- src/admin.rs
- src/client.rs
- src/consumer/stream_consumer.rs
- src/producer/future_producer.rs
- tests/test_admin.rs
- tests/test_consumers.rs
- tests/test_high_producers.rs
- tests/test_metadata.rs
- tests/utils.rs
Upgrade to the new async/await ecosystem, which includes
std::future::Future, futures 0.3, tokio 0.2, and the new async/await
keywords.
This will bump the MSRV to Rust 1.39.
Co-authored-by: Ben Sully &lt;ben@bsull.io>
Co-authored-by: Danny Browning &lt;bdbrowning2@gmail.com>
> Upgrade to async/await ecosystem

- examples/asynchronous_processing.rs
- src/message.rs
librdkafka is entirely thread safe, and guarantees that the memory
referenced by a BorrowedMessage will remain valid as long as the
consumer remains valid. Since BorrowedMessage has a reference to the
consumer inside, Rust will enforce this invariant, and it is therefore
safe to mark BorrowedMessage as Send + Sync.
Also update the asynchronous_processing example to make use of this new
feature. The example now allows spawning multiple workers, which
requires tokio::spawn, which turn requires that the generated future
implement Send, which finally requires the adjustment made in this
patch.
Fix #85.
Fix #189.
> Implement Send + Sync on BorrowedMessage

- rdkafka-sys/build.rs
The approach in #176 to handle MSVC was flawed, as it did not properly
account for CMake's RelWithDebInfo configuration type. The correct
approach is to ask CMake to install the library, rather than just
building it, at which point the library will be at a stable path
(OUT_DIR/lib) regardless of the directory structure that the particular
CMake generator uses.
Fix #191.
> Use CMake's install target for proper MSVC handling

- changelog.md
- examples/at_least_once.rs
- examples/simple_consumer.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- tests/test_consumers.rs
This PR attempts to remove exposing `*mut rdkafka_sys::RDKafkaTopicPartitionList` in `ConsumerContext::commit_callback` and expose `rdkafka::topic_partition_list::TopicPartitionList` instead.
Should resolve #197
> Improve ConsumerContext::commit_callback

- .travis.yml
The Travis CI Windows environment has changed in a way that causes CMake
to fail. Try using the MSVC toolchain instead.
> ci: explicitly request msvc toolchain on windows

- examples/asynchronous_processing.rs
- src/message.rs
The rationale here is the same as the rationale for implementing Sync on
BorrowedMessage (2779f77ba9).
Fix #200.
> Implement Sync on OwnedHeaders

- Cargo.toml
- examples/asynchronous_processing.rs
- rdkafka-sys/build.rs
Use `cp` instead of `git clone` to create a copy of the librdkafka
folder, since the `.git` folder is not present during `cargo package`.
Also point rdkafka to the new rdkafka-sys version.
> Fix packaging for rdkafka-sys. Point rdkafka to the new version.

- rdkafka-sys/build.rs
We no longer build in tree when using the non-CMake build, so the CMake
build no longer needs to try to remove config.h, because it's almost
certain not to exist.
> rdkafka-sys: don't bother removing in-tree config.h

- src/config.rs
Debug is needed when ClientConfig is put into Context struct of some web frameworks
> derive Debug for ClientConfig

- src/message.rs
There doesn't seem to be a reason that `OwnedMessage` should not implement `Clone`. Certain use cases like using a `tokio::sync::broadcast` channel require `Clone` to be implemented.
> Add Clone to OwnedMessage

- src/producer/base_producer.rs
Added comments to BaseRecord timestamp to describe kafka expects timestamps in millisecond format.
https://github.com/fede1024/rust-rdkafka/issues/217
> Base record timestamp fix issue #217

- src/consumer/mod.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
Exposing the client is useful for power users who may need to invoke
custom methods via the underlying librdkafka API. For example, it is
often necessary to explicitly call fetch_metadata on a producer's
client.
The client struct was already public, and somewhat accessible via the
consumer context, so this actually increases the consistency of the API.
> Expose underlying client in consumer and producer

- src/topic_partition_list.rs
librdkafka is thread safe. This allows to assign a `TopicPartitionList` to a consumer before calling `start()` in an async/await context under Rust.
For example (inside a `tokio::spawn` thread):
```Rust
let mut tpl = TopicPartitionList::new();
tpl.add_partition_offset("topic", 0, Offset::Beginning);
consumer.assign(&tpl)?;
while let Some(message) = consumer.start().try_next().await? {
// ...
}
```
This fails without the patch:
```
tokio::spawn(async {
^^^^^^^^^^^^ future is not `Send`
```
> Implement Send + Sync on TopicPartitionList

- rdkafka-sys/README.md
Seems like this feature is enabled in the code as [`gssapi-vendored`](https://github.com/fede1024/rust-rdkafka/blob/master/rdkafka-sys/Cargo.toml#L57).
> docs: expose name gssapi-vendored

- src/message.rs
This PR exposes the detach function on BorrowedHeaders. This is already exposed through `detach` on `BorrowedMessage`, but this allows us to incrementally copy the message.
> Make deatch public on BorrowedHeaders

- src/statistics.rs
rdkafka-1.3.0 supports a much richer set of windowing statistics than
this library previously exposed. Most interesting is the percentile
information, which allows users to see approximately how many requests
are falling into performance issues.
Resolves #229
> Report full windowing statistics

- rdkafka-sys/Cargo.toml
librdkafka expects sasl2's GSSAPI plugin to be enabled.
> rdkafka-sys: enable gssapi in sasl2 when vendored

- src/admin.rs
- src/client.rs
- src/config.rs
- src/consumer/base_consumer.rs
- src/consumer/stream_consumer.rs
- src/groups.rs
- src/message.rs
- src/metadata.rs
- src/topic_partition_list.rs
- src/util.rs
Did a pass through the crate and cleaned up a lot of the logic around drops. The `NativePtr` were added as a small abstraction around an owned ptr and where I could, I moved the allocated ptr into this structure as early as possible to ensure drops were not forgotten.
Fixed a few other small things on the way as well.
> refactor: Homogenize the unsafe around drop (and more)

- Cargo.toml
- README.md
- changelog.md
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/lib.rs
- src/util.rs
- tests/test_high_consumers.rs
- tests/test_low_consumers.rs
- tests/utils.rs
Requiring Tokio admits a much simpler implementation that does not
require a separate thread or executor. The dependency on Tokio is
optional (on by default) in order to allow folks who are using only the
BaseConsumer to avoid the Tokio dependency.
Fix #192.
> Require Tokio for stream consumer

- Cargo.toml
- examples/roundtrip.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- tests/test_high_consumers.rs
PR #251 introduced a performance regression in that the new
StreamConsumer implementation could take up to 100ms to notice new
messages after reaching the end of the librdkafka consumer queue.
Rewrite the StreamConsumer to avoid this behavior. By using the
message_queue_nonempty callback, we can poll librdkafka from the same
task that is calling MessageStream.poll, and schedule a wakeup when new
data becomes available.
The latency numbers are now indistinguishable from the implementation
before #251, as measured by the new "roundtrip" example. (Both before
and after report a p99 latency of 2ms, while the implementation in #251
reports a p99 latency of 100ms.)
/cc @redbaron I believe this resolves one of your concerns.
> Restore latency of StreamConsumer after consuming all messages

- docker-compose.yaml
For compatibility with podman-compose. Note that we do not intend to
support podman-compose in general, if there are other incompatibilities,
but this change is straightforward enough to be worthwhile.
Fix #242.
> Use string environment declarations in docker-compose.yml

- changelog.md
- examples/asynchronous_processing.rs
- examples/at_least_once.rs
- examples/simple_producer.rs
- src/producer/future_producer.rs
- src/producer/mod.rs
- tests/test_high_producers.rs
- tests/utils.rs
@FSMaxB-dooshop I incorporated your fix from #222 here, along with a rewrite to use `tokio::time::delay_for` rather than `std::thread::sleep`. Let me know what you think. I added one test so far for the successful case (which was evidently totally untested before), but I'm going to try to add another test for the `QueueFull` case before merging.
----
The `block_ms` parameter of `FutureProducer::send` was previously buggy,
and did not behave at all as the documentation claimed. Make several
improvements:
* Rename the parameter to `queue_timeout`, to better reflect its
purpose in retrying only the queue phase (not the entire send).
* Adjust the type from an `i64` representing milliseconds to
`util::Timeout`, for better consistency with other APIs that allow
configurable timeouts.
* Use …
> Fix blocking behavior of FutureProducer::send

- .travis.yml
- Cargo.toml
- changelog.md
- examples/smol_runtime.rs
- rdkafka.suppressions
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/producer/future_producer.rs
- src/producer/mod.rs
- src/util.rs
- test_suite.sh
- tests/test_high_producers.rs
This is an alternative to #256 I had in the works that does not require rewriting the `StreamConsumer`.
----
rdkafka only depends on Tokio for tokio::time::delay_for and
tokio::task::spawn. It is easy enough to package those up into a trait
so that users can swap in an asynchronous runtime of their choosing.
By default we only supply an implementation of AsyncRuntime for Tokio,
and only if the `tokio` feature is enabled, but this patch introduces an
example that uses the smol runtime. If some of these other runtimes
prove to be popular we can look into shipping "official" AsyncRuntime
implementations for those runtimes behind feature flags.
> Introduce AsyncRuntime trait to allow pluggable async runtimes

- src/producer/future_producer.rs
This makes it show up in rustdoc, plus it's likely nice for end users to
have access to the type alias anyway.
Fix #283.
> Mark OwnedDeliveryResult as public

- src/client.rs
- src/error.rs
- tests/test_low_producers.rs
Add `get_fatal_error` to the `Client` and expose it to consumers and producers for easy access
> add get_fatal_error, closes #279

- Cargo.toml
- changelog.md
- src/consumer/stream_consumer.rs
- tests/test_high_consumers.rs
Before, each concurrent consumer would overwrite the earlier set waker
so only one task at a time would be awoken. By changing this to a Slab
where each `MessageStream` has its own slot, which is recycled on drop,
we can start multiple `MessageStream`s which concurrently polls kafka
and all get woken up when new messages arrive.
Co-authored-by: Nikhil Benesch <nikhil.benesch@gmail.com>
> feat: Allow concurrent use of StreamConsumer

- changelog.md
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
It is not valid to e.g. call `poll` on the BaseConsumer that underlies a
StreamConsumer. Rather than trying to document all the edge cases that
are invalid when accessing a StreamConsumer's underlying consumer, just
disallow access entirely.
> Don't allow access to StreamConsumer's underlying consumer

- rdkafka-sys/Cargo.toml
- rdkafka-sys/changelog.md
Prepare the next version of rdkafka-sys. The features include:
* Upgrading to the latest version of librdkafka, v1.5.3, which is a
maintenance release that fixes several bugs in v1.5.0.
* Upgrading to a version of zstd-sys that does not exhibit the
decompression bug described in #201.
Fix #201.
> rdkafka-sys: prepare v2.1.1+1.5.3

- .github/workflows/ci.yml
- README.md
- changelog.md
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/lib.rs
This facilitates a forthcoming refactor of stream consumers.
> Store consumer contexts as an Arc, rather than a Box

- changelog.md
- examples/smol_runtime.rs
- src/producer/future_producer.rs
- tests/test_metadata.rs
- tests/utils.rs
Make the FutureProducer work more like the new StreamConsumer by making
the AsyncRuntime a type parameter of the FutureProducer, rather than its
methods.
> Adjust FutureProducer for new StreamConsumer

- changelog.md
- examples/at_least_once.rs
- examples/roundtrip.rs
- examples/simple_consumer.rs
- src/consumer/stream_consumer.rs
- tests/test_metadata.rs
Per @Marwes's request, to make it more clear that this method does not
come from the StreamExt trait.
> Rename StreamConsumer::next -> recv

- changelog.md
- src/consumer/base_consumer.rs
- src/topic_partition_list.rs
- tests/test_high_consumers.rs
- tests/test_low_consumers.rs
- tests/test_transactions.rs
This allows specifying negative offsets reading from the end of a partition. It mirrors what the `RD_KAFKA_OFFSET_TAIL` macro does in the C lib.
Unfortunately I wasn't able to fully run all tests because `test_topics` topic fails for me (also on master without my changes applied) with a timeout error despite me having a Kafka instance listening on `localhost:9092`.
Let me know if you want me to change anything!
> Add Offset::OffsetTail

- rdkafka-sys/changelog.md
v2.1.1+1.5.3 had to be yanked to do its unintentional inclusion of the
RDKafkaErrorCode -> RDKafkaError rename. Note this in the changelog, and
prepare for the v3.0.0+1.6.0 that will be released shortly.
Fix #329.
> Note yanking in rdkafka-sys changelog

- Cargo.toml
- rdkafka-sys/Cargo.toml
To match the usage of hyphens in the other feature names. As it turns
out we've misdocumented the existence of the "dynamic-linking" feature
for several releases now.
This approach matches what we've done for the
"cmake_build"/"cmake-build" feature, where the old name is retained for
backwards compatibility.
Closes #328.
> Add "dynamic-linking" feature; deprecate "dynamic_linking" feature

- changelog.md
- src/config.rs
- src/consumer/base_consumer.rs
- src/consumer/stream_consumer.rs
- tests/test_metadata.rs
It would be very useful in some cases to read back params from the final config, otherwise I end up needing to record what's been set in some piece of external state.
> make `get` public to allow reading back config

- rdkafka-sys/build.rs
Linking against the vendored copy of openssl is more carefully handled
in the build_librdkafka function, which does not blindly overwrite
CFLAGS/LDFLAGS.
Fix #338.
> rdkafka-sys: remove stray openssl vendoring code

- changelog.md
- src/config.rs
On aarch64, the char type in C is unsigned. Use the os::raw::c_char
type in a cast, rather than `i8`, to avoid hardcoding assumptions
about the signedness of char.
Since the switch to GitHub Actions we haven't had automatic testing of
aarch64 in CI. (Travis CI latency had become unbearable since its new
owners decided to squeeze every last drop of profit out of the company.)
For now I've just tested this locally, but we may want to consider an
aarch64 runner if issues like this one come up frequently.
> Fix compilation on aarch64, which uses unsigned chars

- rdkafka-sys/build.rs
- rdkafka-sys/changelog.md
The upstream CMake build system does not properly set the
WITH_STATIC_LIB_libcrypto define when linking against a static copy of
OpenSSL, which means the SSL initialization code will not probe for the
system's CA certificate bundle. Work around the issue for now by just
setting the define ourselves.
See: https://github.com/edenhill/librdkafka/pull/3249
> rdkafka-sys: work around upstream OpenSSL issue

- src/consumer/stream_consumer.rs
I was creating a custom `ConsumerContext` to customize the rebalancing logic when I noticed that `StreamConsumer` wraps up my context without providing access to it.
> Allow access into inner context in StreamConsumerContext

- Cargo.lock
- src/client.rs
- src/consumer/mod.rs
This PR adds Debug trait derives to default client and consumer contexts.
My context is following - I've created a custom consumer context that propagates the statistics provided by librdkafka via `tokio::sync::watch` channel. The code that uses consumers either with custom or default context has a data structure with a field parameterised by context. This data structure is logged with debug formatting. This requires Debug trait implemented for both contexts.
> add Debug trait to DefaultClientContext/DefaultConsumerContext

- src/consumer/base_consumer.rs
We've seen a case where the offsets pointer in the commit callback was null. Check for this state and pass an empty topic partiton list into the callback if it happens.
Fixes #406
> Create empty topic partition list for callback if needed

- Cargo.lock
- src/client.rs
- src/config.rs
- src/consumer/base_consumer.rs
Several of the prior uses of mem::forget could result in double drops in
the face of panics. Replace all possible uses of mem::forget with
ManuallyDrop instead.
> Replace mem::forget with ManuallyDrop

- Cargo.lock
- src/statistics.rs
rdkafka publishes stats every configurable ms. Some of these properties
are ever increasing and requires us to calculate the difference between
the current value and the previous value (for example the 'tx' and
'txmsgs' fields). Setting a Default trait allow us to use the default
values for fields of the struct which are required on startup.
> Add Default trait to Statistics

- changelog.md
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- tests/test_high_consumers.rs
- tests/test_low_consumers.rs
- tests/utils.rs
This is a reworking of #351 and #395 with additional testing and more efficient queue wakeups.
> Add split_partition_queue to StreamConsumer

- src/client.rs
The underlying function call `rdsys::rd_kafka_rebalance_protocol` can
return a NULL pointer in the case of an error. The callers within
librdkafka treat this similarly to it returning "NONE", so we will
return `RebalanceProtocol::None` to emulate this behavior.
Closes #416
> Fix handling of NULL pointer in `NativeClient::rebalance_protocol`

- .github/dependabot.yml
- .github/workflows/ci.yml
Add a test that uses Cargo's unstable minimal-versions resolver to
ensure that the dependency specifactions in the Cargo.toml are correct.
It's easy to declare a dependency on v1.0 and then use a feature that's
only available in v1.1.
Also, tweak the dependabot configuration to ignore patch and minor
bumps. As a library, it's important to be as compatible as possible.
That means that for each dependency we want to use the oldest version
that is SemVer compatible with that dependency's latest release.
> ci: test minimal versions

- src/error.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
- src/producer/mod.rs
- tests/test_high_producers.rs
- tests/test_low_producers.rs
- tests/test_transactions.rs
Per the [rdkafka documentation](https://docs.confluent.io/5.5.1/clients/librdkafka/rdkafka_8h.html#aaff06c4372bce917c17f3c1a5d8b205d), `flush` can return `RD_KAFKA_RESP_ERR__TIMED_OUT`.  Pass that through on the `Producer` trait instead of swallowing it.
> [producer] pass through error when calling flush

- Cargo.lock
- Cargo.toml
- changelog.md
- examples/runtime_async_std.rs
- examples/runtime_smol.rs
- src/admin.rs
- src/consumer/stream_consumer.rs
- src/producer/future_producer.rs
- src/util.rs
In the main library, swap the dependency on `futures` for individual
dependencies on `futures-channel`, `futures-util`, and
`futures-executor`. This reduces the dependency load on downstream
projects. Additionally disable the `futures-util::select` macro and use
the slightly more cumbersome function to lose a dependency on
proc-macro-hack and proc-macro nested.
This has two changes from #432:
* The `futures-executor` dependency is optionalized on the new
`naive-runtime` feature.
* The tests and examples continue to use the main `futures` crate,
since there's no need to be so careful with dependencies in
tests/examples. In examples particularly I think it's much clearer
to refer to the main `futures` crate rather than its subcrates.
Closes #432.
Co-authored-by: Rob Ede …
> Reduce futures dependency

- rdkafka-sys/build.rs
pkg_config could fail for various reasons including dependency issues to other libs, not only when librdkafka is not found. Actually, I needed to `brew install openssl` to make it successful. By printing error together, it should be easier to troubleshoot such errors.
> Fix misleading error message on pkg_config failure

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/admin.rs
- src/client.rs
- src/config.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/lib.rs
- src/log.rs
- src/util.rs
Much of the rust ecosystem uses `tracing` over `log`
This branch adds an optional feature `tracing` to `rdkafka` that uses `tracing` log lines instead of `log` ones. See https://github.com/MaterializeInc/materialize/blob/883710649f95d232ead5872518969a15c1def542/src/kafka-util/src/client.rs#L28-L47 for an example of how people have to work around this, over using the `DefaultClientContext`
Some notes:
- `tracing::enabled!` is slightly different than `log::log_enabled!` in that it doesn't query the tracing subscriber for specifically `Event` type's. In practice, I have found this to be a vanishingly small difference, but with https://github.com/tokio-rs/tracing/pull/1900 this pr (after its landed, backported, and released), it could be possible to slightly improve
- `tracing` log levels are …
> add `tracing` feature

- src/client.rs
- src/config.rs
- src/producer/future_producer.rs
This PR is meant to provide the user a way to build a Client that uses the `oauthbearer_refresh_token_cb` functionality in rdkafka-sys. It also provides the plumbing  to define their own callback through the `ClientContext` trait.
- `ClientConfig` has a `pub(crate)` flag that tells the `Client` to set the callback function to that of the given `<impl>ClientContext` type.
- Default implementation of the callback just logs a message at the error level, the user needs to create their own callback function.
Example
```rust
// Define a type that overrides the default refresh_oauth_token method
struct RefreshContext {
// relevant fields
}
impl RefreshContext {
// other impl details
}
impl ClientContext for RefreshContext {
fn refresh_oauth_token(&self, client: &mut RDKafka, oauthbearer_config: …
```
> add support for OAuth

- .github/workflows/ci.yml
- changelog.md
- examples/simple_consumer.rs
- rdkafka-sys/simple_producer.rs
- src/message.rs
- tests/test_high_producers.rs
- tests/test_low_producers.rs
Kafka distinguishes between null header values and empty header values,
but rust-rdkafka was presenting null header values as empty header
values. Rework the API to preserve the distinction.
> Allow distinguishing between null and empty header values

- src/consumer/mod.rs
This commit tweaks the improved commit mode docs added in #449. It makes
the link to the upstream issue about async support more visible. It also
removes the links to specific code in librdkafka. These references weren't
rendering correctly in several places, and I'm nervous about linking to
specific code in librdkafka; we'll upgrade librdkafka soon enough, and
those links may not be relevant. Better to let the text stand on its
own, I think.
> Tweak improved commit mode docs

- src/message.rs
Currently an `OwnedMessage` only allows to get a reference to the attached `OwnedHeaders`. This PR allows to detach the `OwnedHeaders` from the `OwnedMessage`.
> Add detach_headers for OwnedMessage

- src/statistics.rs
Adding `Clone` will enable sharing through atomic replacement with a callback.
How?
https://github.com/vertexclique/callysto/blob/master/src/kafka/contexts.rs#L31-L49
> Enable Atomic swap for statistics coming from librdkafka by enabling `Clone` on `Statistics`

- src/producer/base_producer.rs
- src/util.rs
See #471
For `Arc`, an alternative that doesn't break the existing code would be to leave `as_ptr` as is and use `Arc::as_ptr(self)`, but the relevant `Box` methods take by `self`, so a more thorough analysis is required.
> Fix possible unsoundness in IntoOpaque to do with pointer provenance

- src/consumer/mod.rs
Hello,
Let me start with a quick thank you to all who maintain this Rust crate!
I had been struggling with an off-by-one error which caused my consumer service to double-consume the last message any time the server restarted, when I realized that I misunderstood the semantics of Commit Offsets. 
I found [this thread](https://github.com/confluentinc/confluent-kafka-dotnet/issues/1380#issuecomment-672036089) which finally clarified for me that I need to commit the offset of the next message that I want to receive, **_NOT_** the offset of the most recently consumed message. 
I am very surprised at how difficult it was to find a clear description of this behavior in all of the online Kafka documentation, and I thought I may save somebody else a headache if I call this out explicitly in your …
> Improve documentation for Commit Offset semantics

- changelog.md
- src/client.rs
- src/config.rs
- src/producer/future_producer.rs
@duarten @jsurany-bloomberg these changes are a result of me eyeballing the diff in #442. Any chance one of you is able to test? I don't have easy access to a Kafka broker configured for OAUTHBEARER authentication. Ideally we'd have a test for this in the repository, but that might be more trouble than it's worth to set up.
----
Tweak the support for the OAuth token refresh callback added in #442 to
avoid some memory unsafety and to be more in line with crate
conventions. In particular:
* Don't pass `&str` to C code expecting a C string directly, as the
Rust string slice is not guaranteed to be null terminated and so the
C code might read off the end of a string. Instead always construct
a CString.
* Don't allow the user to specify an `errstr_size`. Crate convention
is to use an `ErrBuf` …
> Rework OAuth callback to avoid memory unsafety and follow conventions

- src/consumer/stream_consumer.rs
The call to `rd_kafka_consumer_close()` in the `Drop` trait of `BaseConsumer` can block in the rebalance callback indefinitely. It's stuck in the call `rd_kafka_rebalance_protocol()` waiting for a queue operation to be completed. We often see this happen when an external process deletes a topic that was currently being consumed in our application, leaving thread trying to drop the `BaseConsumer` in a hung state.
Rust drops fields in a struct in the order they are declared in the source. When the `StreamConsumer` is dropped, it will first call `base.drop()`, which eventually executes `rd_kafka_consumer_close()`, and then calls `queue.drop()`, which eventually executes `rd_kafka_queue_destroy()`. This ordering is incorrect according to the documentation for …
> fix: dropping a consumer can block indefinitely

- changelog.md
- src/util.rs
I discovered this when I tried to add  runtime library version checking in our application. `rdkafka::get_rdkafka_version` silently truncates the integer representation so that it's impossible to properly handle how upstream represents the version ( https://docs.confluent.io/platform/current/clients/librdkafka/html/rdkafka_8h.html#aa2e242fb8620a32b650a40575bc7f98e ):
```
Interpreted as hex MM.mm.rr.xx:
MM = Major
mm = minor
rr = revision
xx = pre-release id (0xff is the final release)
E.g.: 0x000801ff = 0.8.1
```
> Fix truncation of `rdkafka_sys::rd_kafka_version` in `rdkafka::get_rdkafka_version`.

- src/config.rs
This allows to get a reference to the underlying HashMap that could be useful for making a clean up before logging it (for example to replace passwords).
> Add config_map method to ClientConfig

- changelog.md
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- tests/test_high_consumers.rs
The librdkafka `assign` function can be used to clear the list of current assignments by passing null, but this wasn't exposed.
We added an explicit unassign method (similar to what [the cpp](https://github.com/confluentinc/librdkafka/blob/master/src-cpp/KafkaConsumerImpl.cpp#L181) and [confluent kafka go](https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/consumer.go#L151) clients do) which precisely does that.
Also exposed `incremental_assign` and `incremental_unassign` which were left off.
> Expose unassign

- .github/workflows/ci.yml
- README.md
- src/client.rs
- src/util.rs
I was taking a look at the repo and noticed that there are a lot of warnings regarding deprecated Node and Action commands regarding the CI workflow.
Part of resolving this is addressing `actions-rs/toolchain`, which is no longer maintained from my understanding. [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) is actively maintained and works well from my experience, so I think switching over should be fine and resolves the issues. The rest is fixed by just updating `checkout` to `v3`.
This also updates the `rust_version` to 1.54.0, since [this change](https://github.com/fede1024/rust-rdkafka/commit/611aeea5012787ad0f1a3ff74af32b64d41142f8#diff-8731dd08efd465ecbfdd192013294eeb858fd4e18dbd44d7528dc7f763fbf108R440) means that 1.53.0 will no longer build. Not sure if …
> update CI workflow to avoid deprecation warnings and build errors

- src/lib.rs
It can be problematic to try to drop down to `rdkafka-sys` from outside the `rdkafka` crate. This re-export allows leveraging the pointers provided in `rdkafka` with the lower level `rdkafka-sys` functions.
> Re-export the bundled rdkafka-sys modules.

- rdkafka-sys/build.rs
Currently, bzl executes the build script in the wrong directory and fails. This checks for this case and sets the right directory if necessary.
> Support bazel builds

- src/client.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
- src/producer/mod.rs
- tests/test_low_producers.rs
Add interface to specify custom partitioners by extending `ProducerContext` trait with capability to return optional custom partitioner.
> Introduce partitioner interface

- src/message.rs
- src/producer/base_producer.rs
This extends the Builder pattern for BaseRecord, and adds the ability to mutate OwnedMessage after construction.
> Add missing setters for some structs

- .github/workflows/ci.yml
- docker-compose.yaml
- tests/test_admin.rs
cp-kafka 7.5.1 would match kafka 3.5.1 based on https://docs.confluent.io/platform/current/installation/versions-interoperability.html.
> Add support for kafka 3.5 in integration tests

- rdkafka-sys/build.rs
For some reason the wrong make program is used when building using bazel. Making it possible to change the make program allows me to override it which fixes the problem.
> Allow users to override make when using cmake

- Cargo.toml
- changelog.md
- rdkafka-sys/Cargo.toml
- rdkafka-sys/changelog.md
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
> Add rust-version, so that our MSRV is enforced by cargo:

- src/statistics.rs
I realize that there is a `stats_raw` trait method, but it would be better to not have to re-type out the statistics fields myself. This came about because I would like to act on many of the individual fields locally via some aggregations, but then output them back out (along with other fields in a larger status struct) as a JSON-encoded string, e.g.:
```rs
#[derive(Serialize)]
pub struct Status {
pub sample_field: u64,
pub sample_field_2: boolean,
pub statistics: Statistics,
}
```
> Derives `serde::Serialize` on `Statistics`

- src/admin.rs
- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
- src/consumer/stream_consumer.rs
- src/error.rs
- src/message.rs
- src/producer/base_producer.rs
- src/util.rs
- tests/test_high_consumers.rs
- tests/test_low_consumers.rs
- tests/test_metadata.rs
This PR changes how rust-rdkafka interacts with librdkafka. Instead of using the callback API, it moves to the event API. This PR does not change any of the public rdkafka API, but it give us the chance to introduce some optimizations. Some of them might break the current API though and hence this PR does not go into that route yet. For example, consider https://github.com/fede1024/rust-rdkafka/issues/273.
Some other benefits:
* it allows to extend the lifetime of BorrowMessages. For example, consider the `FutureProducer` where we need to [detach](https://github.com/fede1024/rust-rdkafka/blob/93e6cd4f36d04e01fe5e025699bb78be938c1f1a/src/producer/future_producer.rs#L187) the borrowMessage on errors.
* it allows handling the rebalance events outside of the scope of the registered callback. …
> Use rdkafka event API instead of the callback API

- src/consumer/base_consumer.rs
This does not affect the StreamConsumer or any other wrapper consumer. It will only incur on an extra Poll call when there's a rebalance event which is negligible. 
why is this needed?
When using bindings built upon the rust-rdkafka ffi, the caller is responsible for initiating the rebalance calls (*assign). If a high timeout is specified, the rebalance handler will only be triggered once the timeout period has elapsed. This fixes it by always returning on rebalance events.
> Return back to the caller on rebalance events

- examples/simple_consumer.rs
- src/consumer/base_consumer.rs
- src/consumer/mod.rs
This changes the interface of `ConsumerContext` in the following ways:
* The `&NativeClient` parameter in `rebalance` is replaced with a `&BaseConsumer<Self>` parameter.
* `pre_rebalance` and `post_rebalance` also gain `&BaseConsumer<Self>` parameters.
This also requires
* the addition of a `BaseConsumer::native_client` method;
* the addition of a `Sized` bound to `ConsumerContext`.
We're building an abstraction around Kafka at Sentry. It's set up in such a way that offsets are committed in batches, not individually, for performance reasons. This means, however, that when a rebalance happens, there may still be outstanding offsets that need to be committed. We want to do this by means of the `pre_rebalance` hook on `ConsumerContext`, but the problem is that this callback has no access to …
> Pass BaseConsumer to ConsumerContext::rebalance

- src/consumer/base_consumer.rs
- src/mocking.rs
- src/producer/base_producer.rs
In some error cases, the `Base{Consumer,Producer}` were eagerly copying strings, and `unwrap`ing utf8 validation, just to print an error message.
This will avoid the allocation in the common case, and be panic-safe in the presumably unreachable case of invalid utf-8.
> Use `CStr::to_string_lossy` in Base{Consumer,Producer}

- src/config.rs
Kafka can return string with multiple `\0` chars (seen at least on Windows x64), and `CStr::from_bytes_with_nul` panics in that case. `String::from_utf8_lossy()` handles that ok
> Fix panic on getting config value from NativeConfig

- src/config.rs
Looks like this change https://github.com/fede1024/rust-rdkafka/commit/353812ff958b4b65f9e65dd22a60e770ed6ba948 is causing following error (when SimpleConsumer is being run) - at least on OSX 
```
librdkafka validated config value is valid u64: ParseIntError { kind: InvalidDigit }
```
That is because rd_kafka_conf_get returns null terminated string, 
```rust
// Allocate a buffer of that size and call again to get the actual
// string.
let mut buf = vec![0_u8; size];
let res = unsafe {
rdsys::rd_kafka_conf_get(
self.ptr(),
key_c.as_ptr(),
buf.as_mut_ptr() as *mut c_char,
&mut size,
)
};
```
ends with buf equal:
```
[51, 48, 48, 48, 48, 48, 0];
```
I guess reverting this change will cause issues on windows, so maybe my PR will be good enough to handle this.
This pr should also fix this case …
> Remove nul chars from string before parsing to numerical values

- .github/workflows/ci.yml
- Cargo.toml
- changelog.md
- docker-compose.yaml
- rdkafka-sys/Cargo.toml
- rdkafka-sys/src/lib.rs
- src/config.rs
- src/groups.rs
- src/lib.rs
- src/mocking.rs
- src/util.rs
- test_suite.sh
- tests/test_admin.rs
Fixed several issues with the current test suite:
* Missing cmake dependency
* Rust version being too old for some dependencies
* Missing null pointer check in src/groups.rs
* Test timeout being too strict
* CI test jobs not working in parallel
This also fixes a few compiler warnings (unused imports, unused code, etc.) and formatting issues.
> Fix integration tests

- .github/workflows/ci.yml
- rdkafka-sys/build.rs
- src/consumer/mod.rs
- src/message.rs
- src/producer/base_producer.rs
- src/producer/future_producer.rs
- src/statistics.rs
- src/topic_partition_list.rs
- tests/test_admin.rs
- tests/test_high_producers.rs
- tests/test_low_consumers.rs
- tests/test_low_producers.rs
- tests/test_transactions.rs
- tests/utils.rs
Fix various clippy warnings in both source and tests
> Fix clippy warnings

- src/consumer/base_consumer.rs
- tests/test_low_consumers.rs
This PR for the [issue](https://github.com/fede1024/rust-rdkafka/issues/690).
> Enable the development of custom consumers

- src/message.rs
- src/producer/base_producer.rs
Pass ref to benefit from underlying specialization - https://doc.rust-lang.org/1.80.1/src/alloc/ffi/c_str.rs.html#279
> Avoid realloc when creating C-style strings

- README.md
I think https://github.com/fede1024/rust-rdkafka/pull/703 updated Rust's MSRV to 1.70. It might be good to update the Readme accordingly as well.
Closes https://github.com/fede1024/rust-rdkafka/issues/720
> Update MSRV to 1.70

- src/client.rs
- src/consumer/base_consumer.rs
- src/consumer/stream_consumer.rs
- src/producer/base_producer.rs
see https://github.com/fede1024/rust-rdkafka/issues/665
> Fix StreamConsumer wakeup races

- src/producer/base_producer.rs
The threaded producer was not `Clone` due to handling the background thread join handle but that can easily be stored in an `Arc` that the last drop of the client unwraps and terminates the background thread.
`Arc::into_inner` guarantees that exactly one thread will manage to unwrap the handle.
> make `ThreadedProducer` clonable like `BaseProducer`

- src/producer/base_producer.rs
My previous PR implemented `Clone` through `derive` which added an unecessary `C: Clone` bound on the context. This PR fixes it by manually implementing the trait.
> relax clone trait bound on context

- Cargo.lock
- rdkafka-sys/Cargo.toml
Currently, rdkafka pulls in `syn 1.0` via `num_enum 0.5`. Most parts of the Rust ecosystem have moved to `syn 2.0`, and it's annoying to have both in the dependency tree because it's pretty heavy in terms of compile time.
I chose to first update `Cargo.lock` via `cargo update` because it was very outdated, and to show that the actual lockfile diff for the `num_enum` upgrade you would also see elsewhere from this doesn't pull in anything extra. I can update the PR to only do the minimal lockfile upgrade if you prefer.
I also checked for breaking changes. `num_enum` unfortunately doesn't have a changelog, but it seems like the only relevant changes are:
- num_enum 0.6 changed some behavior w.r.t. `#[default]` / `#[num_enum(default)]` attributes, which you aren't using
- num_enum 0.7 …
> sys: Upgrade num_enum to 0.7

- src/message.rs
We pass length of header's key so in such case librdkafka doesn't calculate name's length and relies on the passed value. Additionally it adds null byte at the end - https://github.com/confluentinc/librdkafka/blob/10f988f493695ee2ff180d9927f1e881ab98a36d/src/rdkafka_header.c#L96 so no point of creating c string in rust code.
I think that issue is there since forever - https://github.com/fede1024/rust-rdkafka/commit/56366ae8c1443318aa4036097c6fbc879f93e238#diff-e070e0bbef3fd7da263a02197f5b3ba50d6b086f1a882a639dcf70a03db48704R376. The logic to add \0 in librdkafka code base seems also present since forever - https://github.com/confluentinc/librdkafka/pull/1480/files#diff-7daf545224b7aa45b8eeecc8f32b1e07815e64fc6dae003af54ee4a96810a995R97
> Get rid of CString alloc in OwnedHeader::insert

- Cargo.lock
- Cargo.toml
- tests/test_admin.rs
Backoff has been unmaintained for a while, so this PR replaces backoff with backon.
Related to https://github.com/ihrwein/backoff/issues/66
> chore: Use backon to replace backoff

- src/admin.rs
See https://docs.confluent.io/platform/7.5/clients/librdkafka/html/rdkafka_8h.html#ade8d161dfb86a94179d286f36ec5b28e
> Clarify that alter_configs resets unspecified parameters to default

- changelog.md
- src/client.rs
- src/producer/base_producer.rs
- src/util.rs
Refactor `BaseProducer::poll` to not return early, but instead continue processing events until the passed timeout.
Refactor `BaseProducer::flush` to spend most time in `librdkafka`, and whatever is left in `BaseProducer::poll`.
> Various BaseProducer::flush fixes

- README.md
The originally linked repository hasn't been updated in 5 years and is a fork of the active repository, which is https://github.com/TimelyDataflow/timely-dataflow
> README.dm: Update timely-dataflow link to the current repository.

- README.md
Reverts fede1024/rust-rdkafka#752
The active repo link doesn't contain the [kafakesque](https://github.com/frankmcsherry/timely-dataflow/tree/master/kafkaesque) subproject which uses rust-rdkafka so the README link should remain with the frankmcsherry fork of the repo.
> Revert "README.dm: Update timely-dataflow link to the current repository."

- rdkafka-sys/build.rs
The most recent CMake (released March 28, 2025) drops 3.2 compatibility, which the version of librdkafka in rdkafka-sys (2.3.0) depends on. Recent versions of librdkafka increase the min cmake version to 3.5. Rather than upgrade rdkafka-sys to a new librdkafka or patch that source, this PR simply specifies a new min CMake version in the `build.rs` file.
To check that it's working, you can just run `cargo build --features cmake-build`, which fails on head in master.
> Require a minimum of CMake 3.5 compatibility for librdkafka build.

- Cargo.toml
- README.md
- rdkafka-sys/Cargo.toml
- rdkafka-sys/README.md
- rdkafka-sys/build.rs
This feature allows users to pre-build their own static librdkafka and use it with rust-rdkafka.
In our case, to make it easier for cross compilation we preferred to compile natively librdkafka for each architecture, then re-use it from a container image.
> add feature to statically link against existing librdkafka

- .github/workflows/ci.yml
windows-2019 is deprecated and no longer available.
> CI: upgrade to latest window image

- src/admin.rs
- src/config.rs
Sanitizing the ClientConfig Debug to satisfy: https://github.com/fede1024/rust-rdkafka/issues/763
Implementing a basic AdminClient Debug so that KafkaResult<AdminClient> can call unwrap_err(). Unwrap_err<T, E> requires that the success type T implements Debug. https://doc.rust-lang.org/core/result/enum.Result.html#method.unwrap_err
This is a reopening of https://github.com/fede1024/rust-rdkafka/pull/793
> Sanitize ClientConfig and AdminClient debugging

- src/topic_partition_list.rs
Implemented a FromIterator using topic/partition/offset tuple and topic map iterators.
This satisfies: https://github.com/fede1024/rust-rdkafka/issues/790
> Implement FromIterator for TopicPartitionList
